### ISSUE TITLE
wrong parse of url

### ISSUE THREAD

**Issue by vinpel** [antonio-fr/SimpleBitID#2]
Since port number of web server is hardcoded to 80, other listening port can't work.

For example URI like : bitid://127.0.0.1:8000/callback/nonce/ doesn't work,

here is my proposal of modification for "bitid.py", the goal is to modifiy as less as possible the callback url

from urlparse import urlparse
        o = urlparse(uri)
        assert o.scheme=="bitid"
        conni = httplib.HTTPConnection(o.hostname,o.port,timeout=4)
        conni.request("POST",o.path,paramsj,headers)
        rep = conni.getresponse()
        conni.close()

**Comment by antonio-fr** [comment]
Ok, is it because of port number? It seems I sadly hardcoded it to 80.
When you wrote your url is http://, this is bitid:// instead, right? (if not assertion test would fail).

Thanks for urlparse proposal, I will give a  try :)

**Comment by vinpel** [comment]
sorry yes the url is "bitid://", 
my method is for allowing any port number

thanks for the code btw, really usefull !

**Comment by antonio-fr** [comment]
I'm glad that this basic API is useful at least for one guy.

I've update your issue declaration text, to add cause and consequence of the issue.

I'm fixing it tonight :)

**Comment by antonio-fr** [comment]
Fix in newest version v0.05. Thx
https://github.com/antonio-fr/SimpleBitID/releases/tag/v0.05
